# values.yaml
appName: "data-pusher"
# Database configuration
database:
  host: "svc-postgres-headless"
  port: 5432
  name: "db"
  user: "admin"
  password: "pass123"

# Application configuration
application:
  delay_range: "1-20"
  table: "ais_data"
  csvFile: "/app/combined_ais.csv"

# Service
service:
  type: ClusterIP
  port: 80

# Volumes configuration
volumes:
  csvFile: /Users/garethyeo/Desktop/STARLAB/NORTHSTAR/assets/data/combined_vessels.csv
  dataSources: /Users/garethyeo/Desktop/STARLAB/NORTHSTAR/assets/data/sources
  scriptFile: /Users/garethyeo/Desktop/STARLAB/NORTHSTAR/data-pusher/data-pusher.py

# Kubernetes Deployment configuration
image:
  repository: llzd98/data-pusher:0.1
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 8080
