apiVersion: v1
kind: Service
metadata:
  name: postgrest-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.postgrest.port }}
  selector:
    app: {{ .Values.appName }}
