apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.webserver.port }}
  selector:
    app: {{ .Values.appName }}
