apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: postgis/postgis:16-3.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
          livenessProbe:
            exec:
              command:
                - "pg_isready"
                - "-U"
                - "{{ .Values.postgres.user }}"
            initialDelaySeconds: 30
            periodSeconds: {{ .Values.healthcheck.interval }}
            timeoutSeconds: {{ .Values.healthcheck.timeout }}
            failureThreshold: {{ .Values.healthcheck.retries }}
          readinessProbe:
            exec:
              command:
                - "pg_isready"
                - "-U"
                - "{{ .Values.postgres.user }}"
            initialDelaySeconds: 5
            periodSeconds: {{ .Values.healthcheck.interval }}
            timeoutSeconds: {{ .Values.healthcheck.timeout }}
            failureThreshold: {{ .Values.healthcheck.retries }}
      restartPolicy: Always
