apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbeaver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.dbeaver.port }}
          env:
            - name: DBEAVER_HOME
              value: {{ .Values.dbeaver.dbeaverHome }}
          volumeMounts:
            - name: dbeaver-data-volume
              mountPath: {{ .Values.volumes.dbeaverData }}
      volumes:
        - name: dbeaver-data-volume
          emptyDir: {}
      restartPolicy: Always
